Add cb instruction shifts
toastbucket/dookieboy pull request #32
Opened 2022-06-08 03:03 UTC by ricfehr3

2022-06-13 21:16 UTC, toastbucket commented
its back 😎

2022-06-13 21:33 UTC, toastbucket requested changes

2022-06-13 21:33 UTC, toastbucket commented on src/cpu/test.rs
> +    cpu.set_reg(Register8Bit::B, 0x95);
use tests from manual :)

2022-06-13 21:33 UTC, toastbucket commented on src/cpu/mod.rs
> +    fn shift_right(&mut self, regop: Register8Bit, clear_msb: bool) {
rename to `shit_right`

2022-06-13 21:33 UTC, toastbucket commented on src/cpu/mod.rs
> +    fn shift_left(&mut self, regop: Register8Bit) {
rename to `shit_left`

2022-06-14 00:42 UTC, ricfehr3 commented on src/cpu/test.rs
> +    cpu.set_reg(Register8Bit::B, 0x95);
OUTDATED

2022-06-14 00:42 UTC, ricfehr3 commented on src/cpu/mod.rs
> +    fn shift_right(&mut self, regop: Register8Bit, clear_msb: bool) {
`dookie_right`

2022-06-14 00:42 UTC, ricfehr3 commented on src/cpu/mod.rs
> +    fn shift_left(&mut self, regop: Register8Bit) {
`dookie_left`

2022-06-14 00:48 UTC, toastbucket approved these changes

2022-06-14 00:48 UTC, merged